name: flutter_code_generation
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  riverpod_annotation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  riverpod_generator: ^2.3.5
  retrofit_generator: ^8.0.2
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
